apiVersion: v1
kind: Pod
metadata:
  labels:
    run: med-api
  name: shubhampod
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: shubhampod
    resources: {}
