# File: mywebapp-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    run: med-api
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: 80
